### ISSUE TITLE
1.20.1+

### ISSUE THREAD

**Issue by SettingDust** [Ladysnake/Blabber#5]

**Comment by moderninity** [comment]
Hi to follow up on this, would it be possible to release a 1.20.1 version? I believe the main difference is cloth config v11 instead of 12 and maybe the loader? 
Create hasn't updated to 1.20.2 so my server is staying at 1.20.1 unfortunately

**Comment by Pyrofab** [comment]
Could you check whether the current version works on 1.20.1 ? If so, I'll just update the metadata on curseforge and modrinth.

**Comment by moderninity** [comment]
Wasn't able to launch unfortunately :( 

but I actually learned how to make the changes today but all I did was edit fabric.mod.json and change depends minecraft to 1.20.1 and cardinal components base and entity to 5.2.2 instead of 5.3. 

I'm assuming cardinal components downgrade is the kicker but I have no idea since the log tells me nothing
https://mclo.gs/kUBh5Hp

even deleted my config folder just in case

**Comment by SettingDust** [comment]
> Wasn't able to launch unfortunately :(

Isn't it launched?
